### ISSUE TITLE
Unable to deploy. Always prompting Access Denied

### ISSUE THREAD

**Issue by fredmararac** [funkybob/serverless-s3-deploy#40]
> sls s3deploy
> 
>   Serverless Error ---------------------------------------
> 
>   Access Denied
> 
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>      Issues:        forum.serverless.com
> 
>   Your Environment Information ---------------------------
>      OS:                     win32
>      Node Version:           8.10.0
>      Serverless Version:     1.40.0

I tried adding the recommended IAM policy but still I have the isue. :(

**Comment by erik-thompson-seattle** [comment]
@fredmararac Our teams ran into this issue too. The issue is that the acl default in this plugin is public-read and your bucket probably has S3 block public access turned on which prevents the default `public-read` acl from being set. See: https://github.com/funkybob/serverless-s3-deploy#acl and specify an `acl: private`

**Comment by funkybob** [comment]
I've just published v0.9.0 which defaults to acl: private, thanks to kindly provided PRs.

Hope this helps. If not, please re-open this ticket.
